### ISSUE TITLE
Grenepipe gets stuck in qualimap step

### ISSUE THREAD

**Issue by florianhahn87** [moiexpositoalonsolab/grenepipe#1]
Hey,
looks like grenepipe would be super useful for us. Unfortunately, it seems to always get stuck in one of the final steps, namely in this command:
java -Xms32m -Xmx1200M -classpath /lv01/home/hahn/downloads/grenepipe-0.2.0/.snakemake/conda/683a3dfbf01aef5bbb47865a237a8afc/share/qualimap-2.2.2a-1/* org.bioinfo.ngs.qc.qualimap.main.NgsSmartMain bamqc -bam dedup/WT-1.bam -nt 2 -outdir qc/qualimap/WT-1 -outformat HTML

I attached a screenshot of the part where it gets stuck
![image](https://user-images.githubusercontent.com/82394879/114415499-a67d3800-9ba7-11eb-89e4-9d7944c5425b.png)

Is this a known problem and do you know a solution?

Cheers,
Florian

**Comment by lczech** [comment]
Hi Florian,

glad to hear that you find grenepipe useful!

I am not entirely sure what is going on there and what the issue actually is - so no, this one in particular is not a known problem. It most likely is some snakemake/conda issue, and has nothing to do with grenepipe itself. These things happen from time to time, but that would be up to snakemake and conda to fix...

Firstly, I am not entirely sure what the issue actually is. You write that it comes from the Java command that runs qualimap, but the screenshot shows the merge call step. How did you extract/infer that Java command?

Secondly, if it is due to conda, you could try to remove all conda environments, and have snakemake download them again. For this, do `rm -rf /lv01/home/hahn/downloads/grenepipe-0.2.0/.snakemake/conda`, and then try again.

Hope these hints help - if not, we will have to dig deeper.
Lucas

**Comment by florianhahn87** [comment]
Thanks for the feedback! Seems it was a RAM size problem of Qualimap. We could solve it by assigning more RAM space in the config.yaml file to Qualimap (see below). Thanks a lot!
![image](https://user-images.githubusercontent.com/82394879/114727201-eb36d980-9d35-11eb-84c3-376a3bb6cef1.png)

**Comment by lczech** [comment]
Oh interesting, thanks for the feedback! Yeah, Java can be weird... May I ask how you figured this out? Might be interesting for future reference!

**Comment by lczech** [comment]
Also, can this issue be closed then?

**Comment by florianhahn87** [comment]
We found this error message in the log file:
WARNING: out of memory!
Qualimap allows to set RAM size using special argument: --java-mem-size
Check more details using --help command or read the manual.

That is how we figured it out :)
Sure, it can be closed, thanks!
