### ISSUE TITLE
Updating run with new reads

### ISSUE THREAD

**Issue by Brent-Saylor-Canopy** [moiexpositoalonsolab/grenepipe#14]
Hi, I have found your pipeline very helpful and would like to know the best way to use it when new samples are added regularly.

I have been running it separately for each set of reads I get in, but is there a way to get it to run only the new samples added to samples list?

When I try to add new samples to the samples file and launch the pipeline again I get a message saying there is nothing to be done.

I feel like I'm missing something obvious, as this seems like something snakemake is already good at.

**Comment by lczech** [comment]
For anyone finding this in the future: In recent versions, I have removed the file write-protection, because users were confused by this. This comes at the risk that unnecessary computation is done though, but that can easily checked beforehand by running snakemake with `-n` or `-nd` for a dry-run to check that the rule executions are as expected.
