### ISSUE TITLE
Issues during variant calling

### ISSUE THREAD

**Issue by florianhahn87** [moiexpositoalonsolab/grenepipe#3]
Hey again, we always encounter now an issue when running several samples on the grenepipe pipeline during the variant calling step. Weirdly, it seems to be only concerning one of the files but this is a file that is generated in the pipeline process and not by us (.g.vcf.gz) if i understand that error message correctly. The other weird thing is that after the error, the pipeline seems to continue for a few more steps before it stops. Also, in contrast to other errors that we encountered, this one does not refer to a specific log file so not really sure how to solve this. Did you come across this message before?
![image](https://user-images.githubusercontent.com/82394879/116253009-ffcc9600-a767-11eb-91ab-8ded1a2e51f9.png)

**Comment by lczech** [comment]
Hi Florian,

ah, so what is happening here is the following: There are certain files produced during the pipeline that I thought are important to keep (for example, because their computation takes a relatively long time, and so you want to protect them from accidental deletion in order to avoid re-computation). Hence, I have marked these `.g.vcf` files as protected in snakemake. 

That however has the consequence that when in a later run (e.g., re-running after an error in another job), snakemake determines that this file needs updating (for example, because a newer input file is available), it will attempt to run the job again, but can't, because the file is write-protected... I had been thinking about removing the write-protection, because - as in your case now - it seems to cause more trouble then doing good. It never happened to me that I accidentally deleted files, but it did happen regularly that I ran into the same thing you are seeing now.

The solution is easy, just delete the offending file, and then re-start snakemake. If you delete from the command line, you can use `rm -f ...` to force the removal of a write-protected file.

As for why the pipeline continues for some more steps: This is likely because there are other independent jobs that can be run without needing the broken file. But hard to tell from the information that you provided in your case.

Hope that helps, and let me know if there is any more trouble!
Lucas

PS: Thanks for reporting this. Plus one on my mental tally for "should I remove the write-protection" :-)

**Comment by florianhahn87** [comment]
Thanks for the detailed solution, that solved the problem :) Thanks again!
