### ISSUE TITLE
Write full executed command for each step to log files for reproducibility

### ISSUE THREAD

**Issue by uzbit** [moiexpositoalonsolab/grenepipe#38]
Perhaps this already exists and I haven't found it yet, but it would be really helpful for tuning and debugging a pipeline if we could see the individual commands at each step. 

For example, all of the log/mpileup/*.log files are empty, which i guess means there was no output from the command, but ideally this should contain the command executed too.

Thanks!

**Comment by lczech** [comment]
Hey @uzbit,

that seems more like a request for snakemake in general, rather than for grenepipe in particular :-) 

Snakemake offers the `--printshellcmds`, which might do what you want. Let me know if that helps. If not, I'd suggest to open an issue over on [their GitHub](https://github.com/snakemake/snakemake).

Cheers
Lucas

**Comment by uzbit** [comment]
That was it! thanks!

**Comment by lczech** [comment]
Awesome, that was easy to solve ;-)
