### ISSUE TITLE
a new type of error

### ISSUE THREAD

**Issue by ospfsg** [moiexpositoalonsolab/grenepipe#45]

**Comment by lczech** [comment]
Hi @ospfsg,

what do you mean by 

> terminal close by himself.

Without any error message, the terminal just closes? That does not seem like anything that would happen from running snakemake or grenepipe. Could you somehow maybe give me some steps for how I could reproduce this behavior, or describe what is happening in more detail?

As for the log files, I am not seeing anything attached yet, also not in the duplicate issue #46 (which I have closed already, as it seemed exactly identical to this one). Could you please try again and upload all relevant log files? That is, the main log file, and, assuming that the issue is with freebayes, also those log files?

If the terminal really closes before you can get the log output, you can also find a copy of the log file in your run directory (the one that you specify with `--directory`), in a hidden sub-directory called `.snakemake/log`, where it should be the last one there (they are named and sorted by date of creation). The freebayes log files are in `logs/freebayes`. Please append all relevant log files here, so that I can have a look.

So long
Lucas
