### ISSUE TITLE
problem in running v0.13.1

### ISSUE THREAD

**Issue by ospfsg** [moiexpositoalonsolab/grenepipe#56]
Hi

after installing the v0.13.1

**Comment by ospfsg** [comment]
Hi 

After installing v0.13.1. I run the command I used to run in version 12 with the new config file adapted.  I attached the log file. 
[2024-10-06T112814.831312.log](https://github.com/user-attachments/files/17268956/2024-10-06T112814.831312.log)

I get two error messages. The first related with snakemake. I checked your issues #2957 and it should not be a reason for the pipeline not running or is it ?

second  error is new and is related creation of conda envs.... 

do you mind to check the log file ?
thank you
osp

**Comment by lczech** [comment]
Hi @ospfsg,

The first issue you mention (https://github.com/snakemake/snakemake/issues/2957) can likely be ignored, as that is some Snakemake-internal warning, but does not seem to affect the runs.

The second one is new, and only seems to exist since a week. Quick google search revealed that other people have reported this already in the main Snakemake repository (https://github.com/snakemake/snakemake/issues/3108). That seems yet again to be one of those utterly annoying things where the whole conda/mamba ecosystem breaks backwards compatibility... honestly, if I had known that conda and mamba cause so much trouble, I would not have started using it... but well, it is what it is.

As this is an issue between Snakemake and mamba, I cannot do anything as far as grenepipe is concerned to solve this. You can try to downgrade mamba to an older version, or use [micromabma](https://mamba.readthedocs.io/en/latest/installation/micromamba-installation.html) instead to set up your environment for grenepipe.

Let me know how that goes :-)
Lucas

**Comment by ospfsg** [comment]
Hi 

After installing v0.13.1. I run the command I used to run in version 12 with the new config file adapted.  I attached the log file. 
[2024-10-06T112814.831312.log](https://github.com/user-attachments/files/17268956/2024-10-06T112814.831312.log)

I get two error messages. The first related with snakemake. I checked your issues #2957 and it should not be a reason for the pipeline not running or is it ?

second  error is new and is related creation of conda envs.... 

do you mind to check the log file ?
thank you
osp





> Hi @ospfsg,
> 
> The first issue you mention ([snakemake/snakemake#2957](https://github.com/snakemake/snakemake/issues/2957)) can likely be ignored, as that is some Snakemake-internal warning, but does not seem to affect the runs.
> 
> The second one is new, and only seems to exist since a week. Quick google search revealed that other people have reported this already in the main Snakemake repository ([snakemake/snakemake#3108](https://github.com/snakemake/snakemake/issues/3108)). That seems yet again to be one of those utterly annoying things where the whole conda/mamba ecosystem breaks backwards compatibility... honestly, if I had known that conda and mamba cause so much trouble, I would not have started using it... but well, it is what it is.
> 
> As this is an issue between Snakemake and mamba, I cannot do anything as far as grenepipe is concerned to solve this. You can try to downgrade mamba to an older version, or use [micromabma](https://mamba.readthedocs.io/en/latest/installation/micromamba-installation.html) instead to set up your environment for grenepipe.
> 
> Let me know how that goes :-) Lucas

Dear Lucas thank for your reply. 

I go to install  micromamba, but then I should keep the same option in the snakemake command:  --use-conda   --conda-frontend mamba   --conda-prefix  .../conda-envs/ 

or change to:

--use-micromamba  --conda-frontend micromamba    ...

thank you
osp

**Comment by lczech** [comment]
Hi @ospfsg,

the command should be the same, i.e., `--use-conda --conda-frontend mamba`. The way to get snakemake to use micromamba is by using micromamba to install the grenepipe environment, activate that environment, and then run grenepipe as usual from there. See [here](https://github.com/moiexpositoalonsolab/grenepipe/wiki/Setup-and-Usage#preparing-the-environment). 

Cheers
Lucas

**Comment by lczech** [comment]
Hi Octavio,

is this issue solved then, given the new issue in #58? Let me know if we can close this, or if you have further questions :-)

Cheers
Lucas

**Comment by lczech** [comment]
Okay, I assume we can close this then :-) 

If not, as always, feel free to comment, re-open, or start a new issue!

Cheers
Lucas
