### ISSUE TITLE
Columns in output file don't add up

### ISSUE THREAD

**Issue by Easybel** [moiexpositoalonsolab/grenepipe#57]
I am running diversity on bam files to determine the diversity across the whole genome (--window-type genome) and expected the columns to add up to the total number of positions on my genome. 
This is not the case and I think that I am missing the .missing positions. 
Why is this the case? Depending on my averaging policy it is important to take these into account, right?

**Comment by lczech** [comment]
Hi @Easybel,

it seems you posted to the wrong repository - you probably were looking for https://github.com/lczech/grenedalf this one? I can image that the similar names are confusing though, sorry for that! ;-)

Would you mind posting your question over there again, so that it's in the right place, and can be found by others as well? Also, while you are at it: From what you are describing, I can not yet fully answer your question. It could be due to the missing positions, or some filter, or other things that are apparently not well explained in the documentation yet. But to know what exactly is the cause there, I'd need the full command that you are running, along with a minimal example that exhibits the behavior you are observing.

See you over in the other repository! 
So long
Lucas

**Comment by Easybel** [comment]
Thanks for redirecting me! I now re-posted my question and added some details. Hope that helps!
I got here in the first place because I followed the link on your main github page (compare with picture) and that led me here :) But I should have realized I was not in the right place, sorry for the inconvenience!!
And by the way, I really like your tool and especially the documentation!! Great job
![image](https://github.com/user-attachments/assets/96fdcd76-94e0-411e-9e32-83d909ce6fa1)
