### ISSUE TITLE
vcf file with all positions

### ISSUE THREAD

**Issue by florianhahn87** [moiexpositoalonsolab/grenepipe#6]
Hey Luc
as,
I was just wondering, is there a possibility to get as an output of grenepipe a vcf file just like the variance file, but not only with the variances, but with all the information on read depths etc for every position of the genome. I would like it to look something like this:

![image](https://user-images.githubusercontent.com/82394879/123252631-6a8a1b80-d4e4-11eb-920c-67835510d84c.png)

Is there any command line option for this when running grenepipe?

Thanks a lot,
Florian

**Comment by lczech** [comment]
Hi Florian,

that is something that should be solvable with the `extra` options that are offered for each tool. In your case, depending on which tool you use for variant calling, you want to look up the respective command line option for that caller in their documentation, and add that option to the `extra` field for the tool in the grenepipe config file. Not entirely sure which of the callers can do that though.

Hope that helps ;-)
Lucas

**Comment by lczech** [comment]
Hi @florianhahn87, any news on this issue?

**Comment by florianhahn87** [comment]
Hey Lucas, we could not really solve it via grenepipe. What we did is running the grenepipe pipeline as usual and then running haplotypecaller seperately (without grenepipe) on the preprocessed BAM files using gatk HaplotypeCaller --native-pair-hmm-threads 10 -R /path/to/reference/genome  -I /path/to/bam/file   -O /output/file/path  -ERC BP_RESOLUTION --output-mode EMIT_ALL_ACTIVE_SITES --dbsnp /path/to/database/of/known/variants   
All the best,
Florian

**Comment by lczech** [comment]
Oh okay, could you maybe elaborate a bit on why this did not work with grenepipe? I might want to fix that then :-)

**Comment by florianhahn87** [comment]
I tried to run come of the extra commands using the config file
![image](https://user-images.githubusercontent.com/82394879/124831188-cb990100-df72-11eb-855d-5048da58b186.png)

I got the following error message:
![image](https://user-images.githubusercontent.com/82394879/124831259-e23f5800-df72-11eb-8939-d0d5ac2ea937.png)

I think the problem is that there are two values for -ERC, the -ERC BP_RESOLUTION that i want and then -ERC GVCF which I guess comes from the Grenepipe default settings?

**Comment by lczech** [comment]
Oh interesting. Yes indeed, the issue seems to be that of course the two `ERC` modes cannot be set at the same time. Unfortunately, the `ERC` setting is currently not set in grenepipe itself, but in a [wrapper script](https://snakemake-wrappers.readthedocs.io/en/0.51.3/wrappers/gatk/haplotypecaller.html) that we are using. I'd have to change that wrapper in order to solve this. Also, I have no idea what the downstream steps would do if suddenly all sites are included - would have to test this...

So, for now, I am not sure if this is a use case that others have as well (do you happen to have an idea of how useful this would be for others?!), and how easy it would be for me to implement this. Still, I'm reopening the issue as a reminder for myself to get back to this at some point. But seeing that you already found a solution for now, I probably will not get back to this immediately. Let's see. 

Please also keep me updated with other grenepipe issues that you run into! Trying to build a easy and useful tool here :-) 

Lucas
